FROM ubuntu:latest

RUN apt update && apt install -y curl
RUN curl -L -O https://github.com/adelolmo/hd-idle/releases/download/v1.21/hd-idle_1.21_amd64.deb
RUN dpkg --install hd-idle_1.21_amd64.deb && rm hd-idle_1.21_amd64.deb

ENTRYPOINT [ "hd-idle" ]