name: Build and deploy images
on:
  push:
    branches: [main]

jobs:
  build-hd-idle:
    uses: ./.github/workflows/build-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      imageName: hd-idle

