---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and publish Container images

on:
  workflow_call:
    inputs:
      appsToBuild:
        required: true
        type: string
        default: "[]"
      pushImages:
        required: false
        default: false
        type: boolean

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ inputs.appsToBuild  != '[]' }}
    strategy:
      matrix:
        image: ${{ fromJSON(inputs.appsToBuild) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          context: images/${{ matrix.image }}
          image: ${{ matrix.image }}
          tags: latest
          containerfiles: |
            images/${{ matrix.image }}/Containerfile
  
      - name: Push To github repo
        id: push-to-github
        if: ${{ inputs.pushImages }}
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}