---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and publish Container images

on:
  workflow_call:
    inputs:
      appsToBuild:
        required: true
        type: string
        default: ""
      pushImages:
        required: false
        default: false
        type: boolean

jobs:
  prepare-input:
    runs-on: ubuntu-latest
    outputs:
      apps: "${{ steps.prep-apps.outputs.apps }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Populate appsToBuild
        id: prep-apps
        shell: bash
        run: |
          IMAGES=$(find images -mindepth 1 -maxdepth 1 -type d -printf %f\\n | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=${${{ inputs.appsToBuild }}:-IMAGES}" >> $GITHUB_OUTPUT

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: ["prepare-input"]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: ${{ fromJSON(needs.prepare-input.outputs.apps) }}
    steps:
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          context: images/${{ matrix.image }}
          image: ${{ github.repository }}/${{ matrix.image }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./images/${{ matrix.image }}/Containerfile
  
      - name: Push To github repo
        id: push-to-github
        if: ${{ inputs.pushImages }}
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}