---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and deploy on push
on:
  push:
    branches: [main]

concurrency:
  group: container-release
  cancel-in-progress: false

jobs:
  get-changed-images:
    uses: lehmanju/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    permissions:
      contents: read
      packages: write
    needs: ["get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.get-changed-images.outputs.addedOrModifiedImages) }}
    uses: lehmanju/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      image: "${{ matrix.image }}"
      push: true