---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Get Changed Images"

on:
  workflow_call:
    outputs:
      addedOrModified:
        description: "Whether any files were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModified }}
      addedOrModifiedImages:
        description: "The images that were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModifiedImages }}

jobs:
  get-changed-images:
    name: Get Changed Images
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: "${{ steps.changed-files.outputs.all_changed_and_modified_files_count > 0 }}"
      addedOrModifiedImages: "${{ steps.changed-files.outputs.all_changed_files }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed images
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: images/**
          dir_names: true
          dir_names_max_depth: 2
          matrix: true

      - name: List changed images
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'