---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Scheduled Release

concurrency:
    group: container-release
    cancel-in-progress: false

on:
    workflow_dispatch:
        inputs:
            appsToBuild:
                description: App(s) to build
                required: false
                type: string
                default: all
    schedule:
    - cron: "0 * * * *"

jobs:
    get-changed-images:
        uses: lehmanju/containers/.github/workflows/get-changed-images.yaml@main
    
    build-images:
        permissions:
            contents: read
            packages: write
        needs: ["get-changed-images"]
        if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
        uses: lehmanju/containers/.github/workflows/build-images.yaml@main
        secrets: inherit
        with:
            appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
            pushImages: true