---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Scheduled Release

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build
        required: false
        type: string
#  schedule:
#  - cron: "0 * * * *"

jobs:    
  build-images:
    permissions:
      contents: read
      packages: write
    uses: lehmanju/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      appsToBuild: "${{ inputs.appsToBuild }}"
      pushImages: true